# -*- coding: utf-8 -*-
"""
Распространённые приветствия на разных языках и в латинской транслитерации
для намерения start (без внешних API). Список можно расширять по мере необходимости.
"""

from __future__ import annotations

GREETING_PHRASES: tuple[str, ...] = (
    # --- Японский ---
    "こんにちは",
    "こんばんは",
    "おはよう",
    "おはようございます",
    "やあ",
    "やぁ",
    "もしもし",
    "はじめまして",
    "よろしく",
    "よろしくお願いします",
    "konnichiwa",
    "konbanwa",
    "ohayou",
    "ohayou gozaimasu",
    "moshi moshi",
    "hajimemashite",
    "yoroshiku",
    # --- Корейский ---
    "안녕",
    "안녕하세요",
    "annyeong",
    "annyeonghaseyo",
    "anyeong",
    "anyeonghaseyo",
    # --- Китайский ---
    "你好",
    "您好",
    "早上好",
    "晚上好",
    "嗨",
    "喂",
    "ni hao",
    "nihao",
    "nin hao",
    "zao shang hao",
    "wan shang hao",
    # --- Вьетнамский / тайский / индонезийский ---
    "xin chao",
    "xin chào",
    "sawasdee",
    "sawatdee",
    "สวัสดี",
    "halo",
    "hai",
    "selamat pagi",
    "apa kabar",
    # --- Южная Азия ---
    "namaste",
    "namaskar",
    "नमस्ते",
    "नमस्कार",
    "sat sri akal",
    "assalamu alaikum",
    "assalamualaikum",
    "salam",
    "adaab",
    "vanakkam",
    "வணக்கம்",
    # --- Европа (латиница) ---
    "hello",
    "hi",
    "hey",
    "howdy",
    "good morning",
    "good afternoon",
    "good evening",
    "greetings",
    "hallo",
    "guten tag",
    "guten morgen",
    "guten abend",
    "servus",
    "gruezi",
    "grueetzi",
    "bonjour",
    "salut",
    "coucou",
    "buongiorno",
    "buonasera",
    "ciao",
    "hola",
    "buenos dias",
    "buenas tardes",
    "buenas noches",
    "ola",
    "oi",
    "bom dia",
    "boa tarde",
    "boa noite",
    "dobry den",
    "ahoj",
    "czesc",
    "cześć",
    "siema",
    "witam",
    "dzien dobry",
    "dobry wieczor",
    "labdien",
    "sveiki",
    "labas",
    "tere",
    "hei",
    "moi",
    "hej",
    "halloj",
    "god dag",
    "god morgon",
    "god kvall",
    "hallå",
    "goededag",
    "hoi",
    "dag",
    "merhaba",
    "selam",
    "iyi gunler",
    "kalimera",
    "yassas",
    "geia",
    "buna",
    "salutare",
    "noroc",
    "zdravo",
    "zdrasti",
    "dobar dan",
    "pozdrav",
    "bok",
    "szia",
    "szervusz",
    "saluton",
    "aloha",
    # --- Славянские (кириллица) ---
    "добрый день",
    "доброе утро",
    "добрый вечер",
    "доброго ранку",
    "вітаю",
    "привіт",
    "добры дзень",
    "салам",
    "здраво",
    "здравей",
    "добър ден",
    "мерхаба",
    # --- Скандинавия / финский ---
    "hyvaa paivaa",
    "moi moi",
    "terve",
    "hei hei",
    # --- Иврит / персидский / арабский / грузинский / армянский ---
    "shalom",
    "שלום",
    "salom",
    "salaam",
    "dorood",
    "سلام",
    "gamardjoba",
    "barev",
    "բարև",
    "marhaba",
    "ahlan",
    "ahlan wa sahlan",
    "as salamu alaykum",
    # --- Африка ---
    "jambo",
    "habari",
    "molo",
    "sawubona",
    "dumela",
    # --- Греческий ---
    "γεια",
    "γεια σου",
    "geia sou",
    # --- Кельтский / исландский ---
    "dia dhuit",
    "helo",
    "hae",
    # --- Разное ---
    "namaste ji",
    "kumusta",
    "mabuhay",
    "sain baina uu",
    "salem",
    "сәлем",
)
