# -*- coding: utf-8 -*-
"""
Словарные наборы для дополнительных языков изучения (китайский упрощённый,
испанский, итальянский, португальский, японский). Формат как в vocabulary_seed.

Колонка word_eng хранит форму изучаемого языка (в т.ч. иероглифы/кана).
"""

from __future__ import annotations

from typing import List, Tuple

WordRow = Tuple[str, str, str, str]

# --- Китайский (упрощённый, мандарин) ---
WORDS_ZH: List[WordRow] = [
    ("苹果", "яблоко", "еда", "beginner"),
    ("面包", "хлеб", "еда", "beginner"),
    ("水", "вода", "еда", "beginner"),
    ("茶", "чай", "еда", "beginner"),
    ("咖啡", "кофе", "еда", "beginner"),
    ("牛奶", "молоко", "еда", "beginner"),
    ("米饭", "рис", "еда", "beginner"),
    ("家", "дом", "быт", "beginner"),
    ("门", "дверь", "быт", "beginner"),
    ("书", "книга", "школа", "beginner"),
    ("学校", "школа", "школа", "beginner"),
    ("朋友", "друг", "общение", "beginner"),
    ("大", "большой", "описание", "beginner"),
    ("小", "маленький", "описание", "beginner"),
    ("好", "хороший", "описание", "beginner"),
    ("今天", "сегодня", "время", "beginner"),
    ("明天", "завтра", "время", "beginner"),
    ("一", "один", "числа", "beginner"),
    ("二", "два", "числа", "beginner"),
    ("三", "три", "числа", "beginner"),
    ("红", "красный", "цвета", "beginner"),
    ("蓝", "синий", "цвета", "beginner"),
    ("猫", "кот", "животные", "beginner"),
    ("狗", "собака", "животные", "beginner"),
    ("问题", "проблема", "абстракции", "intermediate"),
    ("时间", "время", "абстракции", "intermediate"),
    ("世界", "мир", "абстракции", "intermediate"),
    ("学习", "учиться", "школа", "intermediate"),
    ("工作", "работа", "работа", "intermediate"),
    ("银行", "банк", "город", "intermediate"),
    ("火车", "поезд", "транспорт", "intermediate"),
    ("飞机", "самолёт", "транспорт", "intermediate"),
    ("发展", "развитие", "абстракции", "advanced"),
    ("现象", "явление", "наука", "advanced"),
    ("假设", "гипотеза", "наука", "advanced"),
    ("哲学", "философия", "наука", "advanced"),
    ("矛盾", "противоречие", "абстракции", "advanced"),
    ("复杂", "сложный", "описание", "advanced"),
    ("责任", "ответственность", "абстракции", "advanced"),
    ("经验", "опыт", "абстракции", "advanced"),
]

# --- Испанский ---
WORDS_ES: List[WordRow] = [
    ("casa", "дом", "быт", "beginner"),
    ("pan", "хлеб", "еда", "beginner"),
    ("agua", "вода", "еда", "beginner"),
    ("leche", "молоко", "еда", "beginner"),
    ("café", "кофе", "еда", "beginner"),
    ("manzana", "яблоко", "еда", "beginner"),
    ("madre", "мать", "семья", "beginner"),
    ("padre", "отец", "семья", "beginner"),
    ("hermano", "брат", "семья", "beginner"),
    ("libro", "книга", "школа", "beginner"),
    ("escuela", "школа", "школа", "beginner"),
    ("puerta", "дверь", "быт", "beginner"),
    ("grande", "большой", "описание", "beginner"),
    ("pequeño", "маленький", "описание", "beginner"),
    ("bueno", "хороший", "описание", "beginner"),
    ("hoy", "сегодня", "время", "beginner"),
    ("mañana", "завтра", "время", "beginner"),
    ("uno", "один", "числа", "beginner"),
    ("dos", "два", "числа", "beginner"),
    ("rojo", "красный", "цвета", "beginner"),
    ("gato", "кот", "животные", "beginner"),
    ("perro", "собака", "животные", "beginner"),
    ("problema", "проблема", "абстракции", "intermediate"),
    ("tiempo", "время", "абстракции", "intermediate"),
    ("mundo", "мир", "абстракции", "intermediate"),
    ("trabajo", "работа", "работа", "intermediate"),
    ("ciudad", "город", "город", "intermediate"),
    ("viaje", "путешествие", "транспорт", "intermediate"),
    ("aeropuerto", "аэропорт", "транспорт", "intermediate"),
    ("decidir", "решать", "глаголы", "intermediate"),
    ("desarrollo", "развитие", "абстракции", "advanced"),
    ("fenómeno", "явление", "наука", "advanced"),
    ("hipótesis", "гипотеза", "наука", "advanced"),
    ("paradoja", "парадокс", "абстракции", "advanced"),
    ("complejo", "сложный", "описание", "advanced"),
    ("responsabilidad", "ответственность", "абстракции", "advanced"),
    ("experiencia", "опыт", "абстракции", "advanced"),
]

# --- Итальянский ---
WORDS_IT: List[WordRow] = [
    ("casa", "дом", "быт", "beginner"),
    ("pane", "хлеб", "еда", "beginner"),
    ("acqua", "вода", "еда", "beginner"),
    ("latte", "молоко", "еда", "beginner"),
    ("caffè", "кофе", "еда", "beginner"),
    ("mela", "яблоко", "еда", "beginner"),
    ("madre", "мать", "семья", "beginner"),
    ("padre", "отец", "семья", "beginner"),
    ("fratello", "брат", "семья", "beginner"),
    ("libro", "книга", "школа", "beginner"),
    ("scuola", "школа", "школа", "beginner"),
    ("porta", "дверь", "быт", "beginner"),
    ("grande", "большой", "описание", "beginner"),
    ("piccolo", "маленький", "описание", "beginner"),
    ("buono", "хороший", "описание", "beginner"),
    ("oggi", "сегодня", "время", "beginner"),
    ("domani", "завтра", "время", "beginner"),
    ("uno", "один", "числа", "beginner"),
    ("due", "два", "числа", "beginner"),
    ("rosso", "красный", "цвета", "beginner"),
    ("gatto", "кот", "животные", "beginner"),
    ("cane", "собака", "животные", "beginner"),
    ("problema", "проблема", "абстракции", "intermediate"),
    ("tempo", "время", "абстракции", "intermediate"),
    ("mondo", "мир", "абстракции", "intermediate"),
    ("lavoro", "работа", "работа", "intermediate"),
    ("città", "город", "город", "intermediate"),
    ("viaggio", "путешествие", "транспорт", "intermediate"),
    ("aeroporto", "аэропорт", "транспорт", "intermediate"),
    ("decidere", "решать", "глаголы", "intermediate"),
    ("sviluppo", "развитие", "абстракции", "advanced"),
    ("fenomeno", "явление", "наука", "advanced"),
    ("ipotesi", "гипотеза", "наука", "advanced"),
    ("paradosso", "парадокс", "абстракции", "advanced"),
    ("complesso", "сложный", "описание", "advanced"),
    ("responsabilità", "ответственность", "абстракции", "advanced"),
    ("esperienza", "опыт", "абстракции", "advanced"),
]

# --- Португальский (европейский вариант, где отличается) ---
WORDS_PT: List[WordRow] = [
    ("casa", "дом", "быт", "beginner"),
    ("pão", "хлеб", "еда", "beginner"),
    ("água", "вода", "еда", "beginner"),
    ("leite", "молоко", "еда", "beginner"),
    ("café", "кофе", "еда", "beginner"),
    ("maçã", "яблоко", "еда", "beginner"),
    ("mãe", "мать", "семья", "beginner"),
    ("pai", "отец", "семья", "beginner"),
    ("irmão", "брат", "семья", "beginner"),
    ("livro", "книга", "школа", "beginner"),
    ("escola", "школа", "школа", "beginner"),
    ("porta", "дверь", "быт", "beginner"),
    ("grande", "большой", "описание", "beginner"),
    ("pequeno", "маленький", "описание", "beginner"),
    ("bom", "хороший", "описание", "beginner"),
    ("hoje", "сегодня", "время", "beginner"),
    ("amanhã", "завтра", "время", "beginner"),
    ("um", "один", "числа", "beginner"),
    ("dois", "два", "числа", "beginner"),
    ("vermelho", "красный", "цвета", "beginner"),
    ("gato", "кот", "животные", "beginner"),
    ("cão", "собака", "животные", "beginner"),
    ("problema", "проблема", "абстракции", "intermediate"),
    ("tempo", "время", "абстракции", "intermediate"),
    ("mundo", "мир", "абстракции", "intermediate"),
    ("trabalho", "работа", "работа", "intermediate"),
    ("cidade", "город", "город", "intermediate"),
    ("comboio", "поезд", "транспорт", "intermediate"),
    ("aeroporto", "аэропорт", "транспорт", "intermediate"),
    ("decidir", "решать", "глаголы", "intermediate"),
    ("desenvolvimento", "развитие", "абстракции", "advanced"),
    ("fenómeno", "явление", "наука", "advanced"),
    ("hipótese", "гипотеза", "наука", "advanced"),
    ("paradoxo", "парадокс", "абстракции", "advanced"),
    ("complexo", "сложный", "описание", "advanced"),
    ("responsabilidade", "ответственность", "абстракции", "advanced"),
    ("experiência", "опыт", "абстракции", "advanced"),
]

# --- Японский ---
WORDS_JA: List[WordRow] = [
    ("りんご", "яблоко", "еда", "beginner"),
    ("パン", "хлеб", "еда", "beginner"),
    ("みず", "вода", "еда", "beginner"),
    ("おちゃ", "чай", "еда", "beginner"),
    ("コーヒー", "кофе", "еда", "beginner"),
    ("ぎゅうにゅう", "молоко", "еда", "beginner"),
    ("いえ", "дом", "быт", "beginner"),
    ("ドア", "дверь", "быт", "beginner"),
    ("ほん", "книга", "школа", "beginner"),
    ("がっこう", "школа", "школа", "beginner"),
    ("ともだち", "друг", "общение", "beginner"),
    ("おおきい", "большой", "описание", "beginner"),
    ("ちいさい", "маленький", "описание", "beginner"),
    ("いい", "хороший", "описание", "beginner"),
    ("きょう", "сегодня", "время", "beginner"),
    ("あした", "завтра", "время", "beginner"),
    ("いち", "один", "числа", "beginner"),
    ("ふたつ", "два", "числа", "beginner"),
    ("みっつ", "три", "числа", "beginner"),
    ("あか", "красный", "цвета", "beginner"),
    ("ねこ", "кот", "животные", "beginner"),
    ("いぬ", "собака", "животные", "beginner"),
    ("もんだい", "проблема", "абстракции", "intermediate"),
    ("じかん", "время", "абстракции", "intermediate"),
    ("せかい", "мир", "абстракции", "intermediate"),
    ("べんきょう", "учёба", "школа", "intermediate"),
    ("しごと", "работа", "работа", "intermediate"),
    ("ぎんこう", "банк", "город", "intermediate"),
    ("でんしゃ", "поезд", "транспорт", "intermediate"),
    ("ひこうき", "самолёт", "транспорт", "intermediate"),
    ("はってん", "развитие", "абстракции", "advanced"),
    ("げんしょう", "явление", "наука", "advanced"),
    ("かせつ", "гипотеза", "наука", "advanced"),
    ("てつがく", "философия", "наука", "advanced"),
    ("むじゅん", "противоречие", "абстракции", "advanced"),
    ("ふくざつ", "сложный", "описание", "advanced"),
    ("せきにん", "ответственность", "абстракции", "advanced"),
    ("けいけん", "опыт", "абстракции", "advanced"),
]
